server:
  port: 8000
  read-timeout: 10
  write-timeout: 10

auth:
  token-ttl: 14400

db:
  host: db 
  port: 5432
  user: postgres
  db-name: postgres
  ssl-mode: disable
  connection-timeout: 60

app:
  min-search-symb: 3